### ISSUE TITLE
Using icons inside of a touchable component

### ISSUE THREAD

**Issue by jwoertink** [stowball/react-native-svg-icon#11]
putting the `<Icon..` inside of a `<TouchableHighlight>` will throw this error 
```
Touchable child must either be native or forward setNativeProps to a native component
```

```javascript
render() {
  return (
    <TouchableHighlight onPress={()=> this._onButtonPress()}>
        <Icon name="ChevronDown" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#999" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </TouchableHighlight>
  );
}
```

I tried following [this example](https://facebook.github.io/react-native/docs/direct-manipulation.html#forward-setnativeprops-to-a-child) to `setNativeProps`, but I still end up with 
```
null is not an object (evaluating this._root.setNativeProps)
```

Here's an example of my `<Icon>`

```javascript
import React from 'react';
import SvgIcon from 'react-native-svg-icon';
import SVGIcons from '../lib/SVGIcons';

export default class Icon extends React.Component {
  setNativeProps = (nativeProps) => {
    this._root.setNativeProps(nativeProps);
  }
  
  render() {
    return (
      <SvgIcon ref={component => this._root = component} {...this.props} svgs={SVGIcons} />
    );
  }
}
```

Here's my `SVGIcons`

```javascript
import React from 'react';
import { Polyline } from 'react-native-svg';

export default {
  ChevronDown: <Polyline points="6 9 12 15 18 9" />,
  ChevronUp: <Polyline points="18 15 12 9 6 15" />
}
```

Is there already a way to do this that I'm missing? Or is this something that would need to be added in?

**Comment by stowball** [comment]
This is just an unfortunate issue of React Native. The safest approach is to always put a `<View>` as the first child, then put your `<Icon>` in that.

**Comment by jwoertink** [comment]
Yeah, I noticed that. I had a few of my Icons inside of a `<Text>` which shows some other weird side affects. 

After messing with this, I found a workaround that works... I don't know if it's good or not. If I just don't do anything in the `setNativeProps`, and remove the `ref` from the component, then it seems to work. This probably is a react native issue though.

```javascript
import React from 'react';
import SvgIcon from 'react-native-svg-icon';
import SVGIcons from '../lib/SVGIcons';

export default class Icon extends React.Component {
  setNativeProps = (nativeProps) => {
    // do nothing here, and that seems to work
  }
  
  render() {
    return (
      <SvgIcon {...this.props} svgs={SVGIcons} />
    );
  }
}
```

I'm rolling with this for now so I'll close it. Hopefully someone else comes up with a better solution later.
