### ISSUE TITLE
Element Invalid  - v0.50.3

### ISSUE THREAD

**Issue by cleandersonlobo** [stowball/react-native-svg-icon#12]
Started showing this error after an update to 0.50.3.

Problem is here:

`<SvgIcon {...props} svgs={svgs} />`

It was working, but now it only accepts string `svgs={"..."}`

Any idea what that might be? 

![screenshot_1510179854](https://user-images.githubusercontent.com/1569889/32578175-00ab9d8e-c4bb-11e7-8e12-cf0e4238ab06.png)

**Comment by stowball** [comment]
Sorry, only just saw this. Looks like upgrading react-native-svg to >= 5.5.1 is required
