### ISSUE TITLE
width , height 

### ISSUE THREAD

**Issue by haofeng123** [stowball/react-native-svg-icon#17]
can i  set a width or height when i create an  SVG icons?

example: 

export default {
    SortArrows: <G><Path d="M0 45h90L45 0 0 45z"/><Path d="M0 55h90l-45 45L0 55z"/></G>,
    Tick: {
        svg: <Path d="M38.729 75.688a4.48 4.48 0 0 1-3.21-1.356L16.558 55.004c-1.774-1.807-1.774-4.736-.001-6.543a4.48 4.48 0 0 1 6.42 0l15.753 16.056 37.749-38.474a4.478 4.478 0 0 1 6.419 0c1.773 1.806 1.773 4.736 0 6.543L41.939 74.332a4.48 4.48 0 0 1-3.21 1.356z"/>,
       // viewBox: '0 0 50 50',
        width:100,
        height:100.
    },
}

**Comment by haofeng123** [comment]
![q](https://user-images.githubusercontent.com/23020922/39513214-30479f1c-4e26-11e8-867b-40074eab7644.jpg)

**Comment by stowball** [comment]
No, you can't. imo, `width` and `height` are not really icon specific things. The size should be determined by the designer when they're used. You may want to change their size at different screen sizes too

**Comment by haofeng123** [comment]
oh,thank you very much
