### ISSUE TITLE
Passing fill is not working on Android

### ISSUE THREAD

**Issue by yerevin** [stowball/react-native-svg-icon#18]
Hello, 
trying to figure out why on android (on ios it is working) passing fill props to SvgIcon is not working after I updated my env to newest RN@55^ and    
 "react-native-svg": "^6.3.1",
 "react-native-svg-icon": "^0.8.1"
For example on icon like that
```
  inventoryIcon: {
    svg: (
      <G>
        <G>
          <Path
            d="M9.9,14.4h.9a.9.9,0,0,1,.9.9H18v1.8H11.7a.9.9,0,0,1-.9.9H7.2a.9.9,0,0,1-.9-.9H0V15.3H6.3a.9.9,0,0,1,.9-.9h.9V12.6H1.8a.9.9,0,0,1-.9-.9V8.1a.9.9,0,0,1,.9-.9H16.2a.9.9,0,0"
            style="fill:#848c87"
          />
        </G>
      </G>
    ),
    viewBox: "0 0 18 18"
  },
```

I'm not able to change color

**Comment by stowball** [comment]
Does it work if you just render that straight out in react-native-svg, bypassing this library?

**Comment by yerevin** [comment]
```
              <Svg viewBox="0 0 16.5 18" width="20" height="20">
                <G>
                  <G>
                    <Path
                      d="M9.9,14.4h.9a.9.9,0,0,1,.9.9H18v1.8H11.7a.9.9,0,0,1-.9.9H7.2a.9.9,0,0,1-.9-.9H0V15.3H6.3a.9.9,0,0,1,.9-.9h.9V12.6H1.8a.9.9,0,0,1-.9-.9V8.1a.9.9,0,0,1,.9-.9H16.2a.9.9,0,0,1,.9.9v3.6a.9.9,0,0,1-.9.9H9.9v1.8M1.8,0H16.2a.9.9,0,0,1,.9.9V4.5a.9.9,0,0,1"
                      fill={this.props.activeTabIndex === key ? "#FFFFFF" : "#848c87"}
                    />
                  </G>
                </G>
              </Svg>
```

Looks like working on android

Before updating packages when I had property style="fill:#848c87" on svg icons, I was able to pass fill

**Comment by stowball** [comment]
You're using a `fill` attribute in your 2nd example and a `style` attribute in your first. I don't think `style` works in RN

**Comment by yerevin** [comment]
but without it, I'm not able to pass custom fill color with your lib, before updating my env it was working, probably problem is inside react-native-svg, but I don't understand why on IOS it is working as before env update

**Comment by stowball** [comment]
The component accepts a `fill` prop, which gets applied to the root element.

Here's how I use in my current project:

```js
import React from 'react';
import SvgIcon from 'react-native-svg-icon';
import svgs from '@assets/svg/svgs';

const Svg = (props) => <SvgIcon {...props} svgs={svgs} />;

Svg.defaultProps = {
  defaultViewBox: null,
  fill: '#000',
  stroke: null,
  strokeWidth: null,
  style: null,
  viewBox: null,
};
```

and then use it like so:

```js
<Svg
  name="chevronDown"
  fill="#fff"
  height={14}
  width={14}
/>
```

**Comment by yerevin** [comment]
I'm using it exactly the same way like you, based on your article.
Can you tell me your env like react-native, react-native-svg and your package versions and if it is working for you on android?

**Comment by stowball** [comment]
Hmmm, I'm using:

```js
"react-native": "0.50.4",
"react-native-svg": "5.5.1",
"react-native-svg-icon": "0.8.0",
```

I'll try and test with your versions tomorrow

**Comment by yjacobowitz** [comment]
Any solution to this? I am having the same issue

**Comment by stowball** [comment]
@yjacobowitz can you please provide a reduced test case and the versions you're using? Thanks

**Comment by yjacobowitz** [comment]
I am using: 
` "react-native": "0.57.5",`
`"react-native-svg": "^6.2.2",`
`"react-native-svg-icon": "^0.7.0",`

**Comment by yjacobowitz** [comment]
@stowball nevermind I updated to the latest version and it works, thanks!

**Comment by stowball** [comment]
👍
