### ISSUE TITLE
Add support for stroke property

### ISSUE THREAD

**Issue by joemckie** [stowball/react-native-svg-icon#2]
`fill` works for the most part, but for simple line icons (like an `x` button), `stroke` must be used.

**Comment by stowball** [comment]
I've actually never used a stroke in my icon systems. I always convert strokes to fills because you have better control over the shape of the ends of paths etc.

In saying that, I should support it

**Comment by stowball** [comment]
Would you just want `color` support, or `width` as well?

**Comment by joemckie** [comment]
I use it for rounded corners on lines mainly!

I think probably just `color` for now. I can't see the width needing to be changed much as it's fairly linked to the design.
