### ISSUE TITLE
PropType warning on style prop when using react-native web

### ISSUE THREAD

**Issue by rsml** [stowball/react-native-svg-icon#21]
When using StyleSheet.create(), react-native-web optimizes each of the styles to a number. So adding PropTypes.number as a valid type for the style prop would fix this warning:
![image](https://user-images.githubusercontent.com/134487/111053621-1918bd80-841a-11eb-82ff-70b3d2516d32.png)

**Comment by stowball** [comment]
v0.10.0 released with this change
