### ISSUE TITLE
Update dependencies to react-native-svg@5.x

### ISSUE THREAD

**Issue by dccarmo** [stowball/react-native-svg-icon#3]

**Comment by el-psy-k** [comment]
same problem!
react-native-svg@4.x not support react-native@0.41.

**Comment by the-medieval-knievel** [comment]
agreed! dependencies need an update

**Comment by joemckie** [comment]
I'll submit a PR for this tonight :smile:

**Comment by stowball** [comment]
Done. Updated to the latest and greatest
